name: Pull Request

on:
  pull_request:

jobs:
  diff:

    runs-on: ubuntu-latest

    steps:
    # Checkout and build files of a base ref.
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.sha }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: actions/cache@v2
      id: cache-pipenv-base
      name: pipenv cache (base)
      with:
        path: |
          ~/.local/share/virtualenvs
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies (base)
      run: |
        python -m pip install -U pip
        pip install -U pipenv
    - name: Install project dependencies (base)
      if: steps.cache-pipenv-base.outputs.cache-hit != 'true'
      run: |
        pipenv sync
    - name: Build (base)
      run: |
        pipenv run invoke build
      env:
        PELICAN_OUTPUT_PATH: 'output_base'

    # Checkout and build files of a head ref.
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        clean: false # Prevent removing files in 'output_base' folder.
    - uses: actions/cache@v2
      id: cache-pipenv-head
      name: pipenv cache head
      with:
        path: |
          ~/.local/share/virtualenvs
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies (head)
      run: |
        python -m pip install -U pip
        pip install -U pipenv
    - name: Install project dependencies (head)
      if: steps.cache-pipenv-head.outputs.cache-hit != 'true'
      run: |
        pipenv sync
    - name: Build (head)
      run: |
        pipenv run invoke build
      env:
        PELICAN_OUTPUT_PATH: 'output_head'

    # Capture page differences.
    - id: diffpages
      name: Diff Pages
      uses: mastercoms/diff-pages-action@v1.0.1-rc.3
      with:
        base-path: 'output'
        head-path: 'output_head'
        pattern: '*{/index.html,.html,/glowstone-202170/index.html}'

    - name: Upload Pages Diff
      continue-on-error: true
      uses: edunad/actions-image@v1.0.1
      with:
          path: './${{ steps.diffpages.outputs.path }}/**/*.jpg'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          title: 'Pages Diff'
