name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: actions/cache@v2
      id: cache-pipenv
      name: pipenv cache
      with:
        path: |
          ~/.local/share/virtualenvs
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install project dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv sync
    - name: Build and publish
      run: |
        pipenv run make github
